language: c
branches:
  only:
  - master
  - experimental

dist: xenial

matrix:
  include:
    - env:
        GHC_VER=8.4.4
        CABAL_VER=2.2
        ALEX_VER=3.2.5
        HAPPY_VER=1.19.12
      addons:
        apt:
          packages:
            - cabal-install-2.2
            - ghc-8.4.4
          sources:
            - hvr-ghc

      cache:
        directories:
          - $HOME/.cabsnap

      before_install:
        - export PATH=/opt/ghc/$GHC_VER/bin:/opt/cabal/$CABAL_VER/bin:/opt/alex/$ALEX_VER/bin:/opt/happy/$HAPPY_VER/bin:~/.cabal/bin/:$PATH;

      install:
        - cabal update
        - sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config

        # installing dependencies
        - cabal install alex-$ALEX_VER happy-$HAPPY_VER cpphs

        # installing Agda
        # Even if there seems to be duplicated code for master & experimental,
        # DO NOT refactor: they regularly get out of sync (typically master
        # builds with the released version while experimental uses some dev
        # version).

        # No matter the path, we should generate a $HOME/installplan.txt to
        # check whether the cache needs updating.

        - if [[ $TRAVIS_BRANCH = "master" ]]; then
             cd ../ &&
             git clone https://github.com/agda/agda &&
             cd agda &&
             git checkout 5053aa9d2a901cfb4c54848e8455820f0183f1b3 &&
             cabal install --only-dependencies --dry -v > $HOME/installplan.txt ;
          fi

        # checking whether .ghc is still valid
        - sed -i -e '1,/^Resolving /d' $HOME/installplan.txt; cat $HOME/installplan.txt
        - touch $HOME/.cabsnap/installplan.txt
        - mkdir -p $HOME/.cabsnap/ghc $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin
        - if diff -u $HOME/.cabsnap/installplan.txt $HOME/installplan.txt;
          then
            echo "cabal build-cache HIT";
            rm -rfv .ghc;
            cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
            cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
          else
            echo "cabal build-cache MISS";
            rm -rf $HOME/.cabsnap;
            mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
          fi

        - if [[ $TRAVIS_BRANCH = "master" ]]; then
            cabal install ;
          fi

        - if [[ $TRAVIS_BRANCH = "experimental" ]]; then
            cabal install ;
          fi

        # snapshot package-db on cache miss
        - echo "snapshotting package-db to build-cache";
          mkdir $HOME/.cabsnap;
          cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
          cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin $HOME/installplan.txt $HOME/.cabsnap/;

        - if [[ $TRAVIS_BRANCH = "master" ]]; then
            cd ../ ;
          fi

        - if [[ $TRAVIS_BRANCH = "experimental" ]]; then
            cd ../ ;
          fi

        # installing fix-whitespace
        - git clone https://github.com/agda/fix-whitespace --depth=1
        - cd fix-whitespace
        - cabal install fix-whitespace.cabal
        - cd ../

        # generating Everything.agda
        - cd cat

        # setting up travis-specific scripts and files
        - cp travis/* .

        - sed -i 's%git@\(.*\):\(.*\)%https://\1/\2%' .gitmodules
      before_script:
        - export AGDA_OPTIONS="-Werror"
        - export RTS_OPTIONS="+RTS -M3.5G -H3.5G -A128M -RTS"

      script:
        - make
