on: [push]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    name: Typechecking
    steps:
    - name: "Clone repository"
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run Agda
      id: typecheck
      uses: ayberkt/agda-github-action@v1.2
      with:
        main-file: src/Cat.agda
        source-dir: .
    - name: Upload HTML
      id: html-upload
      uses: actions/upload-artifact@v1
      with:
        name: html
        path: html